# 1️⃣ aws-auth ConfigMap
# This maps AWS IAM users to Kubernetes users and GROUPS
# The group name defined here is used later in RoleBinding

apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::471112667143:role/eksctl-sampleapp-nodegroup-robosho-NodeInstanceRole-6ojwIEnxdj5n
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee    # 👈 Group created here
      userarn: arn:aws:iam::471112667143:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::471112667143:user/akash
      username: akash
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::471112667143:user/akash
      username: ravi
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::471112667143:user/akash
      username: rajesh
kind: ConfigMap
metadata:
  #creationTimestamp: "2025-12-14T12:12:39Z"
  name: aws-auth
  namespace: kube-system
  #resourceVersion: "1086"
  #uid: c8868eac-de37-440c-96f1-e80d7900a632
