apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::471112667143:role/eksctl-sampleapp-nodegroup-robosho-NodeInstanceRole-6ojwIEnxdj5n
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-14T12:12:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1086"
  uid: c8868eac-de37-440c-96f1-e80d7900a632
