apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: roboshop
  name: roboshop-admin-rolebinding
subjects:
  - kind: User
    name: suresh
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin-role
  apiGroup: rbac.authorization.k8s.io